name: Create EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4
      with:
        repository: Viktoriya1Lesheva/actions-terraform

    - name: Terraform init
      run: terraform init